version: '3'
services:
   etl:
      build:
        context: .
        dockerfile: Dockerfile
      depends_on:
         - postgres
      links:
         - postgres
      environment:
        POSTGRESS_USERNAME: $POSTGRESS_USERNAME
        POSTGRESS_PASSWORD: $POSTGRESS_PASSWORD
        POSTGRESS_DATABASE: $POSTGRESS_DATABASE
        POSTGRESS_HOST: $POSTGRESS_HOST
        MASTER_NODE: $MASTER_NODE
        APP_NAME: $APP_NAME
        TABLE_NAME: $TABLE_NAME
   postgres:
      container_name: films
      image: postgres:9.4
      restart: always
      ports:
         - 5432:5432
      environment:
        POSTGRES_USER: $POSTGRESS_USERNAME
        POSTGRES_PASSWORD: $POSTGRESS_PASSWORD
        POSTGRES_DB: $POSTGRESS_DATABASE
